### PR TITLE
Reset button

### PR DESCRIPTION
**Pull request by Cleop**

### CODE REVIEW

**Comment by jsms90** [comment]
Redundant

```
active = false
```

inside the reset function?
Because calling reset calls stop, which already sets

```
active = false
```

**Comment by Cleop** [comment]
`active` is not redundant because we need to be able to decipher in the event of a bug whether both stop and reset are broken or just stop.

**Comment by jsms90** [comment]
But `seconds=0` can show us

**Comment by Cleop** [comment]
This would only be visible via the display, not solely through our current tests. We could write an additional specific test however this isn't needed as the existing code already does the trick! Fewer lines of code = better 🤔

**Comment by jsms90** [comment]
Cheeky little `active = false` !!!

**Comment by jsms90** [comment]
Good point! Merge-y merge

**Pull request merged**
